# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
      - image: circleci/mongo:4.2.1
      - image: circleci/redis:4.0.9
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn initialize
      - run:
          name: tests
          command: yarn test
      - run:
          name: redeploy-app
          command: ssh -o "StrictHostKeyChecking no" -v $DROPLET_USER@$DROPLET_IP “cd /var/www/sjsiceteam.com/app; git pull origin master; yarn initialize; yarn build; pm2 restart 0"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
